import type { Metadata, Viewport } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";
import { inter, outfit } from "@/lib/fonts";
import { SITE } from "@/lib/constants";
import "./globals.css";

/**
 * app/layout.tsx
 * ─────────────────────────────────────────────────────────────────────────
 * QUÉ CAMBIÓ respecto al layout.tsx original:
 *
 * 1. METADATA (punto D4 del brief — SEO):
 *    El original solo tenía `title: "Cinergia"` y una descripción
 *    genérica heredada del template de create-next-app ("Generated by
 *    create next app" — literalmente el placeholder por defecto, nunca
 *    reemplazado). Ahora incluye:
 *      - `title.template`, para que cada página interna muestre
 *        "Nosotros · CINERGIA" en vez de repetir "CINERGIA" a secas.
 *      - Open Graph + Twitter Card, para que al compartir el link en
 *        WhatsApp/LinkedIn/Instagram se vea una tarjeta con imagen,
 *        título y descripción en vez de un link pelado.
 *      - `metadataBase`, requerido por Next.js para resolver URLs
 *        relativas de OG images de forma absoluta.
 *
 * 2. DATOS ESTRUCTURADOS (JSON-LD):
 *    Se agrega un bloque <script type="application/ld+json"> con schema.org
 *    tipo "EducationalOrganization". Esto no cambia nada visible, pero
 *    ayuda a que buscadores como Google entiendan que CINERGIA es una
 *    organización estudiantil real, mejorando cómo aparece en resultados
 *    de búsqueda (rich snippets).
 *
 * 3. ACCESIBILIDAD: el "skip link" (enlace oculto que aparece solo al
 *    navegar con Tab) permite a una persona que usa teclado o lector de
 *    pantalla saltar directo al contenido, sin tener que tabular por
 *    todos los enlaces del Navbar en cada página — un requisito estándar
 *    de accesibilidad web (WCAG 2.4.1) que el sitio original no tenía.
 *
 * 4. El <Footer /> se monta AQUÍ (layout raíz) en vez de en cada page.tsx
 *    individualmente. Antes cada página tenía que acordarse de importar y
 *    renderizar el Footer manualmente (y la página de Nosotros, de hecho,
 *    ni siquiera lo hacía — no tenía footer).
 * ─────────────────────────────────────────────────────────────────────────
 */

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.name} · ${SITE.university}`,
    template: `%s · ${SITE.name}`,
  },
  description: SITE.description,
  keywords: [
    "CINERGIA",
    "UCSUR",
    "Universidad Científica del Sur",
    "asociación estudiantil",
    "ingeniería",
    "eventos universitarios Perú",
  ],
  openGraph: {
    type: "website",
    locale: SITE.locale,
    url: SITE.url,
    siteName: SITE.name,
    title: SITE.fullName,
    description: SITE.description,
    images: [{ url: "/fondo.cinergia.inicio.jpg", width: 1200, height: 630, alt: SITE.fullName }],
  },
  twitter: {
    card: "summary_large_image",
    title: SITE.fullName,
    description: SITE.description,
  },
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport: Viewport = {
  themeColor: "#003360", // brand-dark: color de la barra del navegador en móviles compatibles.
};

/** Datos estructurados schema.org — ayudan a buscadores a entender qué es CINERGIA. */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "EducationalOrganization",
  name: SITE.fullName,
  url: SITE.url,
  description: SITE.description,
  parentOrganization: {
    "@type": "CollegeOrUniversity",
    name: SITE.university,
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" className={`${inter.variable} ${outfit.variable}`}>
      <body className="font-sans antialiased">
        {/* Skip link: invisible hasta recibir foco por teclado (Tab). */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-md focus:bg-brand-orange focus:px-4 focus:py-2 focus:text-sm focus:font-bold focus:text-white"
        >
          Saltar al contenido principal
        </a>

        <Navbar />
        <main id="main-content">{children}</main>
        <Footer />

        {/* Analítica ligera, sin cookies de terceros ni banner de consentimiento
            requerido (Vercel Analytics es "cookieless" por diseño). Se activa
            automáticamente en producción al desplegar en Vercel; en local no
            envía datos. Ver README para desactivarla si se despliega fuera de Vercel. */}
        <Analytics />

        {/* dangerouslySetInnerHTML es seguro acá: el contenido es JSON-LD
            estático generado por nosotros mismos (organizationJsonLd, arriba),
            nunca texto que haya escrito una persona usuaria del sitio. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
      </body>
    </html>
  );
}
