import type { Metadata } from "next";
import { montserrat } from "./font";
import NavBar from "@/component/Navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Cinergia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
    >
     <body className={`${montserrat.className} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
